### ISSUE TITLE
Offset magic number

### ISSUE THREAD

**Issue by dreamorosi** [thebuilder/react-scroll-percentage#102]
Hi, thanks for building this, I was looking at the code and I have a question regarding [the part](https://github.com/thebuilder/react-scroll-percentage/blob/master/src/index.js#L92) in which to calculate the percentage of scrolling you multiply by 0.25, why so?
```js
const offsetTop = threshold * vh * 0.25
```

Thanks in advance!

**Comment by thebuilder** [comment]
Good question. I'll admit, it's some time since i wrote this. 
I think the basic idea is for elements with threshold > 0, to trigger the scroll percentage before the element is fully inside the viewport.

I'm working on a rewrite, and I'll properly have another look at this specfic part. See if it makes any sense to keep, and document if it does.

**Comment by dreamorosi** [comment]
Thanks for getting back to me so quickly.

I figured it must have been something similar. I was working on a component that uses the scroll percentage to trigger something when the top of the observed component reaches say half of the viewport which I do more or less like this:
```js
const threshold = Math.round(viewportHeight() * 0.5, 2);
const height = getElHeight(ref.current);
const percentageToBeScrolledToDoSomething = (threshold - threshold * 0.25) / height;
```

I think it makes sense to trigger the scroll percentage beforehand but at the same time this kinda makes the percentage value slightly skewed and hard to rely on.

That said, I would be happy to open a PR to document it, I would like to hear your thoughts about it first.

On a side note, I know that this could also be achieved by using the base intersection observer and setting thresholds but I am trying to do some animations and using the percentage made more sense.

**Comment by thebuilder** [comment]
You can find a published **Hook** version here, without the magic number, so you just get the plain offset back.
https://www.npmjs.com/package/@charlietango/use-scroll-percentage

I'm working on rewriting the library into TS, and what that is done this hook will be part of it.

**Comment by dreamorosi** [comment]
Yes, I was already using that hook version but I opened the issue here since I realized it was depending on your other intersection observer component/hook and that the implementation was the same as your non-hook one.

Thanks for promptly pushing the change there, I think I will close the issue!
