### ISSUE TITLE
Any chance of returning the scroll percentage before the ref enters the viewport?

### ISSUE THREAD

**Issue by Andkoo** [thebuilder/react-scroll-percentage#136]
It would be really useful for my use case if the percentage could be returned before the ref element enters the viewport, because I am setting the app theme based on scroll position of a certain element. It works perfectly fine when the element is in the viewport, however when it sits above or below the viewport upon mounting, then the percentage isn't returned and therefore I can't set the theme without implementing some manual solution.

**Comment by thebuilder** [comment]
Doesn't it return `0` as the percentage before it enters the viewport?
Do you have an example? Using hooks?

**Comment by Andkoo** [comment]
It doesn't return `0` before entering the viewport, which I think is the intended behavior. However it would be nice if it actually did return the value at least once upon page load (`0` when the element is below the viewport, `1` when it's above the viewport). Also, yes, using hooks.

**Comment by thebuilder** [comment]
The hook will always return a value, and the value will default to `0`. What value are you seeing?

See the storybook - it starts outside view: https://thebuilder.github.io/react-scroll-percentage/?path=/story/usescrollpercentage--example-vertical

**Comment by Andkoo** [comment]
I've created a [demo](https://codesandbox.io/s/nostalgic-pascal-b72yu) which should help understand my issue better. When the element starts crossing the viewport, it should start changing the background of the app (the darker areas are there to illustrate the area, which should influence the background while scrolling through it). It's hard to fully illustrate the issue since when the demo is reloaded, the scroll position is always at the top. However the scroll position is remembered upon reloading in my project and yes, the hook does always return `0` as a default value, but when the watched element is above the viewport upon loading, then it would be helpful if it would return `1`.

**Comment by thebuilder** [comment]
Right - I get what you're asking for. That would make sense, and is an easy fix.

**Comment by Andkoo** [comment]
Awesome, thanks! 👏

**Comment by Andkoo** [comment]
A new feaure request in my project revealed that the initial value is always `0` even when the element is in the viewport. Am I doing something wrong?

**Comment by thebuilder** [comment]
Does it update correctly when you start scrolling? Does the element have the correct size?

It executes the same function to determine the position on init as when it scrolls, so the result should be the same.

**Comment by Andkoo** [comment]
Yes, it updates correctly upon scrolling, it's only the initial value which is incorrect. I might be doing something wrong, but I'm not sure what's the culprit.

**Comment by thebuilder** [comment]
Hmm. Will have to investigate why it doesn't trigger that correctly.

I can replicate on this page when viewed on Edge: https://thebuilder.github.io/react-scroll-percentage/iframe.html?id=usescrollpercentage--example-vertical

But that page seems to be working in Chrome, unlike your example.

**Comment by Andkoo** [comment]
I don't know if this will help, but I can replicate the bug even in Chrome.

![image](https://user-images.githubusercontent.com/17043364/70910310-c6cad000-200f-11ea-96de-5478d4c2c498.png)

Environment: MacBook Air 2017, macOS Mojave 10.14.3, Google Chrome 79

**Comment by superfunkminister** [comment]
I have a similar issue, I need to start scrolling before a value other than `0` is returned rather than getting the value on page mount.

**Comment by thebuilder** [comment]
Sorry - I haven't had time to look into this specific issue yet.😧

**Comment by jacobbuck** [comment]
I've been having this issue too, but only with the `useScrollPercentage` hook. Using the render props of the `<ScrollPercentage>` component has the correct percentage on mount. 🤔

**Comment by superfunkminister** [comment]
Hey @thebuilder is this fixed now?
