### ISSUE TITLE
npm package does not contain /es folder

### ISSUE THREAD

**Issue by fgnass** [thebuilder/react-scroll-percentage#31]
The ES6 build is missing in both `1.0.0` and `1.0.1`, rendering these versions unusable in a Webpack 2 setup. (Version `0.6.0` is the last published version that contains the `/es` folder.) 

It looks as if the `prepublish` script wasn't executed at all. AFAIK `prepublish` is deprecated and has been replaced by `prepare` and `prepublishOnly` but I guess it should still work though? There is also a `yarn-error.log` in the published packages, but this also seems to be unrelated.

**Comment by fgnass** [comment]
BTW, the same applies to `react-intersection-observer` – the `/es` folder is missing there too.

**Comment by thebuilder** [comment]
Hey @fgnass - I intentionally removed the `/es` folder, but i must have forgotten to remove it from `package.json` in this project. I'll update it! Thanks

**Comment by thebuilder** [comment]
Fixed in 1.0.2
