### ISSUE TITLE
support horizontal scroll percentage?

### ISSUE THREAD

**Issue by tnrich** [thebuilder/react-scroll-percentage#41]
Hey there,

Just wondering if this package does/could support horizontal scrolling as well.

I didn't see it in the demo so I assume it doesn't.

Thanks!

**Comment by thebuilder** [comment]
Hey @tnrich 

No, this package doesn't support it. I'd like to keep it simple to use, since i mainly use it to trigger effects on vertical page scroll. It should be simple to modify it to work horizontal values if you'd like to tho

**Comment by JulianJorgensen** [comment]
Would love this feature as well. I've created a fork and may submit a PR if there's interest for this feature.
