### ISSUE TITLE
Required code for example

### ISSUE THREAD

**Issue by rahuljain-tt** [thebuilder/react-scroll-percentage#49]
Scrolling is not smooth as explained in example demo: https://thebuilder.github.io/react-scroll-percentage/

Can you please share the code of this demo?

**Comment by thebuilder** [comment]
Hi @rahuljain-tt - you can find the code for the examples in the story file:
https://github.com/thebuilder/react-scroll-percentage/blob/master/stories/ScrollPercentage.story.js

But it doesn't do anything special, compared to the readme example
