### ISSUE TITLE
Incorrect use of babelrc

### ISSUE THREAD

**Issue by rahuljain-tt** [thebuilder/react-scroll-percentage#57]
After using react-scroll-percentage, I am getting below issue in running jest test cases 
Couldn't find preset "./.babelrc.js" relative to directory "/node_modules/react-intersection-observer"

react-scroll-percentage has a babelrc in that, which might be causing issue while transpiling the react-intersection-observer. Below link has detailed explanation of this.

https://github.com/parcel-bundler/parcel/issues/482

**Comment by thebuilder** [comment]
Resolve in 2.0.0
