### ISSUE TITLE
A dependency breaks the build (hooks in alpha)

### ISSUE THREAD

**Issue by fael** [thebuilder/react-scroll-percentage#79]
FOA, thank you for this bright idea.
Because you added support to hooks in react-intersection-observer which got updated to version ^6.1.0, it breaks a project using 16.6.3.

<img width="897" alt="screenshot 2018-12-06 at 15 31 04" src="https://user-images.githubusercontent.com/72215/49593726-278aeb80-f96c-11e8-82ce-d5ddd509e210.png">

Do you think you can lock it? Or it is preferable to users using your lib to shrinkwrap the package? What's your suggestion?

**Comment by thebuilder** [comment]
That's interesting. It shouldn't break unless you are trying to use the hooks. I'll have a look at it.👌

I'm not using the alpha version on my projects, and it doesn't cause this error. 

You should be able to fix it using Yarn resolutions to lock the version of react-intersection-observer for now

**Comment by thebuilder** [comment]
I can't seem to replicate this issue.
Can you recreate it in a [Codesandbox](http://codesandbox.io)?

I've published a new version (3.0.0) which upgrades the build process and dependencies. See if it's still an issue with this version.
