### ISSUE TITLE
Percentage didn't update on resize

### ISSUE THREAD

**Issue by eatlambs** [thebuilder/react-scroll-percentage#87]
Just wondering if we could get the percentage to update on resize of the monitored elements, and resize of encompassing top and bottom elements as well (environment height change) which should effect the percentage in view of the monitored elements. For better usability with responsive layouts.

Seems to works great on react-intersection-observer for visibility status.

Easiest test could be done with the Storybook demo, grab the 'Scroll Down' section and decrease its height.

**Comment by thebuilder** [comment]
Makes sense. I'll add a `resize` listener alongside the scroll listener.

**Comment by eballeste** [comment]
note: this was [implemented](https://github.com/thebuilder/react-scroll-percentage/commit/dce14959b9e1d63cc1047cf3a054702382a9c7c9)!

got really bummed out thinking this was still pending but noticed that percentages updated on resize in demo
