### ISSUE TITLE
reset scrollPosition method?

### ISSUE THREAD

**Issue by eballeste** [thebuilder/react-scroll-percentage#92]
I have this issue where if I scroll all the way down a component to 100% and then I change routes with react-router, then return back the original route while forcing it to scroll all the way up with `window.scrollTo(0, 0)` on componentDidMount, the component will remount, with its topPosition at 0, but the onChange method of the ScrollPercentage node will also be triggered with the retained scrollPosition value of 100% from before I originally had changed routes... this is causing several animation transitions that are supposed to happen based on scroll % to render in its final state even though it rendered at the top of the page...

my question is, why, even if the parent component is remounting, would the ScrollPercentage element seem to be the same one with its original state with the percentage value of 100% and why would the onChange method be triggering on route change if it's still reporting the same value as before? 

hope this makes sense

**Comment by eballeste** [comment]
some extra info: both routes that im switching between have the same children nodes but with different prop values

**Comment by thebuilder** [comment]
If you want to ensure components are remounted add a unique `key` to it. Sounds like that could fix your issue?

**Comment by eballeste** [comment]
adding unique keys for each `ScrollPercentage` node seemed to do nothing, my solution was to call `window.scrollTo(0, 0)` on each of the route containers `componentWillUnmount` method
