### ISSUE TITLE
Needs some love

### ISSUE THREAD

**Issue by thebuilder** [thebuilder/react-scroll-percentage#95]
I haven't used this library in a while, and it's starting to lack behind. 
Needs an overhaul so it becomes synced with `react-intersection-observer`, and exposes a hook version.

Maybe also rewrite in TypeScript.

**Comment by corysimmons** [comment]
hmu if you gain interest in this again and maybe I can help.

**Comment by thebuilder** [comment]
Hey @corysimmons I actually started working on this (see #103).
